name: Commit Lint Check

on:
  pull_request:
    branches:
      - production

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          
      - name: Run commitlint
        run: |
          npx --no-install commitlint --from=HEAD~1
